data:
    dataset: "LSUN" # "ImageNet"
    image_size: 256
    channels: 3
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: true
    rescaled: true
    num_workers: 16
    subset_1k: false
    out_of_dist: true


    category: "bedroom"

model:
    type: "dps_imagenet"
    in_channels: 3
    out_channels: 3
    num_channels: 256
    num_heads: 4
    num_res_blocks: 2
    attention_resolutions: "32,16,8"
    dropout: 0.0
    resamp_with_conv: True
    learn_sigma: True
    use_scale_shift_norm: true
    use_fp16: true
    resblock_updown: true
    num_heads_upsample: -1
    var_type: 'fixedsmall'
    num_head_channels: 64
    image_size: 256
    class_cond: false
    use_new_attention_order: false

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000

sampling:
    batch_size: 8
    last_only: True

# python main.py --ni --config dps_ood_bedroom.yml --doc ood --deg sr8 -i ood_sr8
# python main.py --ni --config dps_ood_bedroom.yml --doc ood --deg sr16 -i ood_sr16

# python main.py --ni --config dps_ood_bedroom.yml --doc ood --deg deblur_gauss --deblur_sigma 1 -i ood_deblur_sigma_1
# python main.py --ni --config dps_ood_bedroom.yml --doc ood --deg deblur_gauss --deblur_sigma 3 -i ood_deblur_sigma_3
# python main.py --ni --config dps_ood_bedroom.yml --doc ood --deg deblur_gauss --deblur_sigma 5 -i ood_deblur_sigma_5

# python main.py --ni --config dps_ood_bedroom.yml --doc ood --deg inp --inpaint_ratio 0.9 -i ood_inp_ratio_0.9
# python main.py --ni --config dps_ood_bedroom.yml --doc ood --deg inp --inpaint_ratio 0.8 -i ood_inp_ratio_0.8
# python main.py --ni --config dps_ood_bedroom.yml --doc ood --deg inp --inpaint_ratio 0.7 -i ood_inp_ratio_0.7
