task: inpaint
seed: 42

# noise_level_img: 0.0
noise_level_img: 12.75
# noise_level_img: 17.85
# noise_level_img: 25.5
noise_level_model: noise_level_img
model_name: 256x256_diffusion_uncond
testset_name: bedroom
num_train_timesteps: 1000
iter_num: 20
iter_num_U: 1
batch_size: 16

save_L: true
save_E: true

lambda_: 1.
zeta: 1.
sub_1_analytic: true
log_process: false
ddim_sample: false
model_output_type: pred_xstart
generate_mode: DiffPIR
skip_type: quad
eta: 0.
guidance_scale: 1.0 # effective guidance scale
n_channels: 3
cwd: ''

calc_LPIPS: true
beta_start: 0.0001
beta_end: 0.02

noise_init_img: max
skip_noise_model_t: false


# inpaint
sf: 1
mask_name: 'gt_keep_masks/face/000000.png'   # mask path for loading mask img
load_mask: false
mask_type: 'random'  #['box', 'random', 'both', 'extreme']
mask_len_range: [128, 129]
mask_prob_range: [0.9, 0.9]
save_progressive_mask: false

