task: denoise
seed: 42

# noise_level_img: 0.0
noise_level_img: 12.75
# noise_level_img: 17.85
# noise_level_img: 25.5
noise_level_model: noise_level_img
model_name: diffusion_ffhq_10m
testset_name: ffhq
num_train_timesteps: 1000
iter_num: 100
iter_num_U: 1
batch_size: 16

save_L: true
save_E: true

lambda_: 1.
zeta: 1.
sub_1_analytic: true
log_process: false
ddim_sample: false
model_output_type: pred_xstart
generate_mode: DiffPIR
skip_type: quad
eta: 0
guidance_scale: 1.0 # effective guidance scale
n_channels: 3
cwd: ''

calc_LPIPS: true
beta_start: 0.0001
beta_end: 0.02

noise_init_img: max
skip_noise_model_t: false


# shot noise
sf: 1
shot_noise_c: 5
